# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Algorys
email: "ttamalfor-not4spam@gmail.com"

#write html inside the double quotes to display in jumbotron
description: "<h1>Algorys Blog</h1><h3>Developpement, Jeux et Nouvelles</h3>"



baseurl: "" # the subpath of your site, e.g. /blog
url: "http://algorys.github.io"
#url: "http://localhost:4000"
twitter_username: agshmne
github_username:  algorys

# Build settings
markdown: kramdown
encoding: utf-8

exclude: ['README.md']
