# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Algorys
tagline:          'Blog'
description:      "<h2>Blog</h2><h3>Développement, Jeux et Nouvelles</h3>"
url:              https://algorys.github.io
baseurl:          # the optional subpath of your site, e.g. "/blog"

author:
  name:           'Estrada Matthieu'
  url:            https://twitter.com/agshmne

paginate:         5

gems:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
version:            3.4.1
sidebar_home_link:  true
github:
  repo:             https://github.com/algorys/algorys.github.io
